# Generated by Django 4.1.2 on 2023-03-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('page_navigation', models.CharField(choices=[('models', 'models'), ('varients', 'varients'), ('details', 'details'), ('Used Cars', 'Used Cars'), ('thankyou', 'thankyou')], default='models', max_length=15)),
                ('image', models.ImageField(upload_to='store/images')),
                ('banners', models.JSONField(blank=True, null=True)),
                ('search_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_keyword', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_for_price', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=255)),
                ('ex_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('page_navigation', models.CharField(choices=[('models', 'models'), ('varients', 'varients'), ('details', 'details'), ('Used Cars', 'Used Cars'), ('thankyou', 'thankyou')], default='models', max_length=15)),
            ],
            options={
                'verbose_name': 'Item Description',
                'verbose_name_plural': 'Item Descriptions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('page_navigation', models.CharField(choices=[('models', 'models'), ('varients', 'varients'), ('details', 'details'), ('Used Cars', 'Used Cars'), ('thankyou', 'thankyou')], default='models', max_length=15)),
                ('search_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='showcase.category')),
                ('promotions', models.ManyToManyField(blank=True, to='showcase.promotion')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ItemDescSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_spec', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('item_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='showcase.itemdescription')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specs',
                'ordering': ['item_desc'],
            },
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='itemlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemlist', to='showcase.itemlist'),
        ),
    ]
