# Generated by Django 4.1.2 on 2023-06-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poststreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststreams',
            name='post_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='Streamspam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poststream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamspam', to='poststreams.poststreams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poststreams.profile')),
            ],
            options={
                'unique_together': {('poststream', 'user')},
            },
        ),
    ]
