# Generated by Django 4.1.2 on 2023-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststreams', '0002_poststreams_post_status_streamspam'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststreamimage',
            name='feelings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
