# Generated by Django 4.1.2 on 2023-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'Retail', 'verbose_name_plural': 'Retails'},
        ),
        migrations.AlterModelOptions(
            name='retailcancel',
            options={'verbose_name': 'Retail Cancel', 'verbose_name_plural': 'Retail Cancels'},
        ),
    ]
