# Generated by Django 4.1.2 on 2023-03-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0002_rename_discount_remarks_paymentrequest_transaction_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='item',
        ),
    ]
