# Generated by Django 4.1.2 on 2023-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0003_remove_paymentrequest_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='cust_id',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
